regenerate .travis.yml (fixes #171)
this is based on @peti's pull request, with small differences.

Most notably, there is a script, `generate-travis-yml`, which preserves
the restriction of Travis to the branches `master` and `travis-test`.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,79 +1,150 @@
-# for reference:
-# https://github.com/ekmett/lens/blob/master/.travis.yml
-
+# This Travis job script has been generated by a script via
+#
+#   runghc make_travis_yml_2.hs '-j' '1:2' '-o' '.travis.yml' 'cabal.project'
+#
+# For more information, see https://github.com/haskell-CI/haskell-ci
+#
 language: c
 sudo: false
 
+git:
+  submodules: false  # whether to recursively clone submodules
+
 cache:
   directories:
-    - $HOME/.ghc
-    - $HOME/.cabal
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
 before_cache:
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -rfv $HOME/.cabal/packages/head.hackage
 
 matrix:
   include:
-    - env: CABALVER=1.22 GHCVER=7.10.3
-      compiler: ": #GHC 7.10.3"
-      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=8.0.2
-      compiler: ": #GHC 8.0.2"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=2.0 GHCVER=8.2.2
-      compiler: ": #GHC 8.2.2"
-      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=2.2 GHCVER=8.4.3
-      compiler: ": #GHC 8.4.3"
-      addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.3,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=2.4 GHCVER=8.6.1 CABAL_PREFIX=v1-
-      compiler: ": #GHC 8.6.1"
-      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.1,happy-1.19.5], sources: [hvr-ghc]}}
-
-#  exclude:
-#    - env: CABALVER=1.18 GHCVER=7.8.4
-
-#  allow_failures:
-#    - env: CABALVER=1.18 GHCVER=7.8.4
+    - compiler: "ghc-8.6.1"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.6.1], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.4.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-7.10.3], sources: [hvr-ghc]}}
 
 before_install:
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
   - unset CC
-  - export HAPPYVER=1.19.5
-  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:$PATH
-  - export PACKAGES="lambdabot-core/ lambdabot-trusted/ lambdabot-*-plugins/ lambdabot/"
-  - function cabal_uninstall() {
-      echo Uninstalling $1;
-      rm -rf $(ghc-pkg describe $1 | sed -En 's/^(library-dirs|data-dir|haddock-html)..//p');
-      ghc-pkg unregister --force $1 2>/dev/null;
-    }
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
 
 install:
-  - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ]; then
-      zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-           $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-    fi
-  - if [ -f $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.gz ]; then
-      zcat $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.gz >
-           $HOME/.cabal/packages/hackage.haskell.org/01-index.tar;
-    fi
-  - travis_retry cabal ${CABAL_PREFIX}update
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - UNCONSTRAINED=${UNCONSTRAINED-true}
+  - NOINSTALLEDCONSTRAINTS=${NOINSTALLEDCONSTRAINTS-false}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
   - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
-  - for pkg in $(ghc-pkg list --user --simple-output); do echo $pkg; done | sort | tee packages-installed
-  - cabal ${CABAL_PREFIX}install $CABAL_INSTALL_FLAGS --only-dependencies --global --dry-run $PACKAGES | tee packages-needed
-  - sed 's/ (.*)//' packages-needed | grep -v ' ' | sort > packages-needed-sorted
-  - for pkg in $(comm -23 packages-installed packages-needed-sorted); do cabal_uninstall $pkg; done
-  - for pkg in $(ghc-pkg check --simple-output); do cabal_uninstall $pkg; done
-  - echo "broken packages $(ghc-pkg check --simple-output) (should be empty)"
-  - cabal ${CABAL_PREFIX}install $CABAL_INSTALL_FLAGS --only-dependencies --enable-tests $PACKAGES
+  - rm -fv cabal.project cabal.project.local
+  - "sed -i.bak 's/^-- jobs:.*/jobs: 1/' ${HOME}/.cabal/config"
+  - "if [ $HCNUMVER -ge 70800 ]; then sed -i.bak 's/-- ghc-options:.*/ghc-options: -j2/' ${HOME}/.cabal/config; fi"
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - "printf 'packages: \"lambdabot-core\" \"lambdabot-haskell-plugins\" \"lambdabot-irc-plugins\" \"lambdabot-misc-plugins\" \"lambdabot-novelty-plugins\" \"lambdabot-reference-plugins\" \"lambdabot-social-plugins\" \"lambdabot-trusted\" \"lambdabot\"\\n' > cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- lambdabot-core | grep -vw -- lambdabot-haskell-plugins | grep -vw -- lambdabot-irc-plugins | grep -vw -- lambdabot-misc-plugins | grep -vw -- lambdabot-novelty-plugins | grep -vw -- lambdabot-reference-plugins | grep -vw -- lambdabot-social-plugins | grep -vw -- lambdabot-trusted | grep -vw -- lambdabot | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  - if [ -f "lambdabot-core/configure.ac" ]; then
+      (cd "lambdabot-core" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-haskell-plugins/configure.ac" ]; then
+      (cd "lambdabot-haskell-plugins" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-irc-plugins/configure.ac" ]; then
+      (cd "lambdabot-irc-plugins" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-misc-plugins/configure.ac" ]; then
+      (cd "lambdabot-misc-plugins" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-novelty-plugins/configure.ac" ]; then
+      (cd "lambdabot-novelty-plugins" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-reference-plugins/configure.ac" ]; then
+      (cd "lambdabot-reference-plugins" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-social-plugins/configure.ac" ]; then
+      (cd "lambdabot-social-plugins" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot-trusted/configure.ac" ]; then
+      (cd "lambdabot-trusted" && autoreconf -i);
+    fi
+  - if [ -f "lambdabot/configure.ac" ]; then
+      (cd "lambdabot" && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf .ghc.environment.* "lambdabot-core"/dist "lambdabot-haskell-plugins"/dist "lambdabot-irc-plugins"/dist "lambdabot-misc-plugins"/dist "lambdabot-novelty-plugins"/dist "lambdabot-reference-plugins"/dist "lambdabot-social-plugins"/dist "lambdabot-trusted"/dist "lambdabot"/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
 
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-  - cabal ${CABAL_PREFIX}install lambdabot-core/ lambdabot-trusted/ lambdabot-*-plugins/ lambdabot/
+  # test that source-distributions can be generated
+  - cabal new-sdist all
+  - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: lambdabot-core-*/*.cabal lambdabot-haskell-plugins-*/*.cabal lambdabot-irc-plugins-*/*.cabal lambdabot-misc-plugins-*/*.cabal lambdabot-novelty-plugins-*/*.cabal lambdabot-reference-plugins-*/*.cabal lambdabot-social-plugins-*/*.cabal lambdabot-trusted-*/*.cabal lambdabot-*/*.cabal\\n' > cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- lambdabot-core | grep -vw -- lambdabot-haskell-plugins | grep -vw -- lambdabot-irc-plugins | grep -vw -- lambdabot-misc-plugins | grep -vw -- lambdabot-novelty-plugins | grep -vw -- lambdabot-reference-plugins | grep -vw -- lambdabot-social-plugins | grep -vw -- lambdabot-trusted | grep -vw -- lambdabot | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+
+  # cabal check
+  - (cd lambdabot-core-* && cabal check)
+  - (cd lambdabot-haskell-plugins-* && cabal check)
+  - (cd lambdabot-irc-plugins-* && cabal check)
+  - (cd lambdabot-misc-plugins-* && cabal check)
+  - (cd lambdabot-novelty-plugins-* && cabal check)
+  - (cd lambdabot-reference-plugins-* && cabal check)
+  - (cd lambdabot-social-plugins-* && cabal check)
+  - (cd lambdabot-trusted-* && cabal check)
+  - (cd lambdabot-* && cabal check)
+
+  # haddock
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+  # Build without installed constraints for packages in global-db
+  - if $UNCONSTRAINED; then rm -f cabal.project.local; echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks all; else echo "Not building without installed constraints"; fi
+
+# REGENDATA ["-j","1:2","-o",".travis.yml","cabal.project"]
+# EOF
 
 branches:
   only:
