update Travis build
- add ghc 8.8.3
- remove ghc 7.10.3 and 8.0.2

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,11 +2,17 @@
 #
 #   haskell-ci '--jobs' '1:2' '-o' '.travis.yml' 'cabal.project'
 #
+# To regenerate the script (for example after adjusting tested-with) run
+#
+#   haskell-ci regenerate
+#
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.3.20190624
+# version: 0.10
 #
+version: ~> 1.0
 language: c
+os: linux
 dist: xenial
 git:
   # whether to recursively clone submodules
@@ -15,6 +21,7 @@ cache:
   directories:
     - $HOME/.cabal/packages
     - $HOME/.cabal/store
+    - $HOME/.hlint
 before_cache:
   - rm -fv $CABALHOME/packages/hackage.haskell.org/build-reports.log
   # remove files that are regenerated by 'cabal update'
@@ -24,54 +31,37 @@ before_cache:
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar.idx
   - rm -rfv $CABALHOME/packages/head.hackage
-matrix:
+jobs:
   include:
+    - compiler: ghc-8.8.3
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.8.3","cabal-install-3.2"]}}
+      os: linux
     - compiler: ghc-8.6.5
-      addons: {"apt":{"sources":["hvr-ghc"],"packages":["ghc-8.6.5","cabal-install-2.4"]}}
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.6.5","cabal-install-3.2"]}}
+      os: linux
     - compiler: ghc-8.4.4
-      addons: {"apt":{"sources":["hvr-ghc"],"packages":["ghc-8.4.4","cabal-install-2.4"]}}
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.4.4","cabal-install-3.2"]}}
+      os: linux
     - compiler: ghc-8.2.2
-      addons: {"apt":{"sources":["hvr-ghc"],"packages":["ghc-8.2.2","cabal-install-2.4"]}}
-    - compiler: ghc-8.0.2
-      addons: {"apt":{"sources":["hvr-ghc"],"packages":["ghc-8.0.2","cabal-install-2.4"]}}
-    - compiler: ghc-7.10.3
-      addons: {"apt":{"sources":["hvr-ghc"],"packages":["ghc-7.10.3","cabal-install-2.4"]}}
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.2.2","cabal-install-3.2"]}}
+      os: linux
 before_install:
   - HC=$(echo "/opt/$CC/bin/ghc" | sed 's/-/\//')
+  - WITHCOMPILER="-w $HC"
+  - HADDOCK=$(echo "/opt/$CC/bin/haddock" | sed 's/-/\//')
   - HCPKG="$HC-pkg"
   - unset CC
   - CABAL=/opt/ghc/bin/cabal
   - CABALHOME=$HOME/.cabal
   - export PATH="$CABALHOME/bin:$PATH"
   - TOP=$(pwd)
-  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - "HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\\d+)\\.(\\d+)\\.(\\d+)(\\.(\\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')"
   - echo $HCNUMVER
-  - CABAL="$CABAL -vnormal+nowrap+markoutput"
+  - CABAL="$CABAL -vnormal+nowrap"
   - set -o pipefail
-  - |
-    echo 'function blue(s) { printf "\033[0;34m" s "\033[0m " }'           >> .colorful.awk
-    echo 'BEGIN { state = "output"; }'                                     >> .colorful.awk
-    echo '/^-----BEGIN CABAL OUTPUT-----$/ { state = "cabal" }'            >> .colorful.awk
-    echo '/^-----END CABAL OUTPUT-----$/ { state = "output" }'             >> .colorful.awk
-    echo '!/^(-----BEGIN CABAL OUTPUT-----|-----END CABAL OUTPUT-----)/ {' >> .colorful.awk
-    echo '  if (state == "cabal") {'                                       >> .colorful.awk
-    echo '    print blue($0)'                                              >> .colorful.awk
-    echo '  } else {'                                                      >> .colorful.awk
-    echo '    print $0'                                                    >> .colorful.awk
-    echo '  }'                                                             >> .colorful.awk
-    echo '}'                                                               >> .colorful.awk
-  - cat .colorful.awk
-  - |
-    color_cabal_output () {
-      awk -f $TOP/.colorful.awk
-    }
-  - echo text | color_cabal_output
-install:
-  - ${CABAL} --version
-  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
   - TEST=--enable-tests
   - BENCH=--enable-benchmarks
-  - GHCHEAD=${GHCHEAD-false}
+  - HEADHACKAGE=false
   - rm -f $CABALHOME/config
   - |
     echo "verbose: normal +nowrap +markoutput"          >> $CABALHOME/config
@@ -89,10 +79,14 @@ install:
     echo "  prefix: $CABALHOME"                         >> $CABALHOME/config
     echo "repository hackage.haskell.org"               >> $CABALHOME/config
     echo "  url: http://hackage.haskell.org/"           >> $CABALHOME/config
+install:
+  - ${CABAL} --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
   - "echo 'jobs: 1' >> $CABALHOME/config"
+  - GHCJOBS=-j2
   - |
-    echo "program-default-options" >> $CABALHOME/config
-    echo "  ghc-options: -j2"      >> $CABALHOME/config
+    echo "program-default-options"                >> $CABALHOME/config
+    echo "  ghc-options: $GHCJOBS +RTS -M6G -RTS" >> $CABALHOME/config
   - cat $CABALHOME/config
   - rm -fv cabal.project cabal.project.local cabal.project.freeze
   - travis_retry ${CABAL} v2-update -v
@@ -100,15 +94,33 @@ install:
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
-    echo 'packages: "lambdabot-core"' >> cabal.project
-    echo 'packages: "lambdabot-haskell-plugins"' >> cabal.project
-    echo 'packages: "lambdabot-irc-plugins"' >> cabal.project
-    echo 'packages: "lambdabot-misc-plugins"' >> cabal.project
-    echo 'packages: "lambdabot-novelty-plugins"' >> cabal.project
-    echo 'packages: "lambdabot-reference-plugins"' >> cabal.project
-    echo 'packages: "lambdabot-social-plugins"' >> cabal.project
-    echo 'packages: "lambdabot-trusted"' >> cabal.project
-    echo 'packages: "lambdabot"' >> cabal.project
+    echo "packages: lambdabot-core" >> cabal.project
+    echo "packages: lambdabot-haskell-plugins" >> cabal.project
+    echo "packages: lambdabot-irc-plugins" >> cabal.project
+    echo "packages: lambdabot-misc-plugins" >> cabal.project
+    echo "packages: lambdabot-novelty-plugins" >> cabal.project
+    echo "packages: lambdabot-reference-plugins" >> cabal.project
+    echo "packages: lambdabot-social-plugins" >> cabal.project
+    echo "packages: lambdabot-trusted" >> cabal.project
+    echo "packages: lambdabot" >> cabal.project
+  - echo 'package lambdabot-core' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-haskell-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-irc-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-misc-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-novelty-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-reference-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-social-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-trusted' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(lambdabot|lambdabot-core|lambdabot-haskell-plugins|lambdabot-irc-plugins|lambdabot-misc-plugins|lambdabot-novelty-plugins|lambdabot-reference-plugins|lambdabot-social-plugins|lambdabot-trusted)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
@@ -122,59 +134,87 @@ install:
   - if [ -f "lambdabot-social-plugins/configure.ac" ]; then (cd "lambdabot-social-plugins" && autoreconf -i); fi
   - if [ -f "lambdabot-trusted/configure.ac" ]; then (cd "lambdabot-trusted" && autoreconf -i); fi
   - if [ -f "lambdabot/configure.ac" ]; then (cd "lambdabot" && autoreconf -i); fi
-  - ${CABAL} v2-freeze -w ${HC} ${TEST} ${BENCH} | color_cabal_output
+  - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
   - rm  cabal.project.freeze
-  - ${CABAL} v2-build -w ${HC} ${TEST} ${BENCH} --dep -j2 all | color_cabal_output
-  - ${CABAL} v2-build -w ${HC} --disable-tests --disable-benchmarks --dep -j2 all | color_cabal_output
+  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all
+  - travis_wait 40 ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --dep -j2 all
 script:
   - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
   # Packaging...
-  - ${CABAL} v2-sdist all | color_cabal_output
+  - ${CABAL} v2-sdist all
   # Unpacking...
   - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
   - cd ${DISTDIR} || false
-  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
+  - PKGDIR_lambdabot_core="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-core-[0-9.]*')"
+  - PKGDIR_lambdabot_haskell_plugins="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-haskell-plugins-[0-9.]*')"
+  - PKGDIR_lambdabot_irc_plugins="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-irc-plugins-[0-9.]*')"
+  - PKGDIR_lambdabot_misc_plugins="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-misc-plugins-[0-9.]*')"
+  - PKGDIR_lambdabot_novelty_plugins="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-novelty-plugins-[0-9.]*')"
+  - PKGDIR_lambdabot_reference_plugins="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-reference-plugins-[0-9.]*')"
+  - PKGDIR_lambdabot_social_plugins="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-social-plugins-[0-9.]*')"
+  - PKGDIR_lambdabot_trusted="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-trusted-[0-9.]*')"
+  - PKGDIR_lambdabot="$(find . -maxdepth 1 -type d -regex '.*/lambdabot-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
-    echo 'packages: "lambdabot-core-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-haskell-plugins-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-irc-plugins-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-misc-plugins-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-novelty-plugins-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-reference-plugins-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-social-plugins-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-trusted-*/*.cabal"' >> cabal.project
-    echo 'packages: "lambdabot-*/*.cabal"' >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_core}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_haskell_plugins}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_irc_plugins}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_misc_plugins}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_novelty_plugins}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_reference_plugins}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_social_plugins}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot_trusted}" >> cabal.project
+    echo "packages: ${PKGDIR_lambdabot}" >> cabal.project
+  - echo 'package lambdabot-core' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-haskell-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-irc-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-misc-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-novelty-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-reference-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-social-plugins' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot-trusted' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package lambdabot' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
   - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(lambdabot|lambdabot-core|lambdabot-haskell-plugins|lambdabot-irc-plugins|lambdabot-misc-plugins|lambdabot-novelty-plugins|lambdabot-reference-plugins|lambdabot-social-plugins|lambdabot-trusted)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building...
   # this builds all libraries and executables (without tests/benchmarks)
-  - ${CABAL} v2-build -w ${HC} --disable-tests --disable-benchmarks all | color_cabal_output
+  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all
   # Building with tests and benchmarks...
   # build & run tests, build benchmarks
-  - ${CABAL} v2-build -w ${HC} ${TEST} ${BENCH} all | color_cabal_output
+  - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} all
   # cabal check...
-  - (cd lambdabot-core-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-haskell-plugins-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-irc-plugins-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-misc-plugins-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-novelty-plugins-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-reference-plugins-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-social-plugins-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-trusted-* && ${CABAL} -vnormal check)
-  - (cd lambdabot-* && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_core} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_haskell_plugins} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_irc_plugins} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_misc_plugins} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_novelty_plugins} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_reference_plugins} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_social_plugins} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot_trusted} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_lambdabot} && ${CABAL} -vnormal check)
   # haddock...
-  - ${CABAL} v2-haddock -w ${HC} ${TEST} ${BENCH} all | color_cabal_output
+  - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all
   # Building without installed constraints for packages in global-db...
   - rm -f cabal.project.local
-  - ${CABAL} v2-build -w ${HC} --disable-tests --disable-benchmarks all | color_cabal_output
+  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all
 
-# REGENDATA ["--jobs","1:2","-o",".travis.yml","cabal.project"]
+# REGENDATA ("0.10",["--jobs","1:2","-o",".travis.yml","cabal.project"])
 # EOF
 
 branches:
